@url=http://localhost:8080/api/portfolio

##################################################
###                My Portfolios               ###
##################################################

# Get users portfolios - happy path
GET {{url}}/myPortfolios HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.gxsuxXm4Kh1FexGDD_j60rb9RkozSV4vsj9b7Diwi6g
### 

# Get users portfolios - unhappy path - bad auth header - unauthorized
GET {{url}}/myPortfolios HTTP/1.1
Authorization: 2

### 

# Get users portfolios - unhappy path - no auth header - unauthorized
GET {{url}}/myPortfolios HTTP/1.1

##################################################
###                   Create                   ###
##################################################

# Create portfolio - happy path
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.5IvHGk_Dpc0F-2vg6-QopLdFw_LC2cyNZW_P0Xdz184

{
    "userId": 1,
    "name": "Portfolio 1jkljkljkljkl",
    "private": true
}

###

# Create portfolio - unhappy path - mismatch in userId from auth header - forbidden
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.kP8FFpCtBdMCwo9cvF0q_b_OUT6In7RAgxfjA0jUWvo

{
    "userId": 2,
    "name": "Portfolio 1",
    "isPrivate": true
}

###

# Create portfolio - unhappy path - Bad parameters - bad request
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.kP8FFpCtBdMCwo9cvF0q_b_OUT6In7RAgxfjA0jUWvo

{
    "userId": 1,
    "isPrivate": true
}


##################################################
###                  Get By ID                 ###
##################################################

# Get by id - happy path
GET {{url}}/3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.Ztt6reof-1Q-QbPGjzZ2GFbhHf8NqQOC-H5tuLh_CrY
