@url=http://localhost:8080/api/stock

##################################################
###                  Get By ID                 ###
##################################################

# Get stock by id - happy path
GET {{url}}/id/1 HTTP/1.1

###

# Get stock by id - unhappy path - cant find

GET {{url}}/id/100 HTTP/1.1


##################################################
###                Get By Ticker               ###
##################################################

# Get by ticker - happy path
GET {{url}}/AAPL HTTP/1.1

### 

# Get by ticker - unhappy path - cant find
GET {{url}}/JDKLAJFKLDAJKL HTTP/1.1
