@url=http://localhost:8080/api/stock

##################################################
###                  Get By ID                 ###
##################################################

# Get stock by id - happy path
GET {{url}}/id/1 HTTP/1.1

###

# Get stock by id - unhappy path - cant find

GET {{url}}/id/100 HTTP/1.1


##################################################
###                Get By Ticker               ###
##################################################

# Get by ticker - happy path
GET {{url}}/AAPL HTTP/1.1

### 

# Get by ticker - unhappy path - cant find
GET {{url}}/JDKLAJFKLDAJKL HTTP/1.1

##################################################
###                     Add                    ###
##################################################

# Add - happy path
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.GC4UyvO1DO3XqAp8cfh2fFY9eYEcKMguVm2wjcIuUlY

{
    "tickerSymbol": "GOOG",
    "companyName": "Google"
}

###

# Add - unhappy path - bad auth - 401
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: dfjsklfjkl

{
    "tickerSymbol": "GOOG2"
}

###

# Add - unhappy path - duplicate - 400
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.IXWmm6xpIVpWl_pFLpapGXHxJFphD05StArVLpLOwUE

{
    "tickerSymbol": "GOOG"
}



###
# Test yahoo finance
GET {{url}}/search/AA
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidXNlcjFAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0TGFzdCJ9.OxYZVT2CVwhqYi0o5lWGVS0ZXD1ZnetY36hANlfOtQ4
