@url=http://localhost:8080/api/user

# Create a user - happy path
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
    "email": "api@add.com",
    "firstName": "test",
    "lastName": "testLast",
    "password": "password"
}

###

# Login - happy path
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "email": "user1",
    "password": "password1"
}

###

# Login - unhappy path - bad email
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "email": "jdklasjfklas",
    "password": "password1"
}

###

# Login - unhappy path - password mismatch
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "email": "user1",
    "password": "bad password"
}
